# Simple workflow for running unit tests and checking that project builds
name: Test workflow

on:
  # Runs on pushes to main
  push:
    branches: 
      - 'main'

  # Run on updates to pull requests
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bootstrap
        run: ./bootstrap
      - name: Run Tests
        run: ./run-tests

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Boostrap
        run: .\bootstrap
      - name: Run Tests
        run: .\run-tests

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bootstrap
        run: ./bootstrap
      - name: Run Tests
        run: ./run-tests
  
